import { auth } from "../../lib/auth";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";

export const metadata = {
  title: "Legal & Disclaimer — LOI Builder",
  description: "Terms and legal disclaimer for LOI Builder.",
};

export default async function LegalPage() {
  const session = await auth();
  const isLoggedIn = !!session?.user;

  return (
    <>
      <SiteHeader isLoggedIn={isLoggedIn} />
      <main className="marketing-page">
        <h1>Legal &amp; Disclaimer</h1>
        <h2>Non-binding document</h2>
        <p>
          Every Letter of Intent generated by LOI Builder is explicitly non-binding. It outlines
          preliminary terms and conditions for a proposed transaction only. Except for any
          confidentiality provisions stated within the document itself, it does not create
          enforceable obligations for either party. Legally binding commitments arise only from a
          finalized, formal Purchase and Sale Agreement executed separately by both parties.
        </p>
        <h2>Not legal advice</h2>
        <p>
          LOI Builder is a self-help document generation tool. It does not provide legal advice
          and does not constitute the practice of law. The documents it produces are templates
          based on the information you provide, and are not a substitute for review by a
          licensed attorney in your jurisdiction. If your transaction involves significant value,
          complex terms, or jurisdiction-specific requirements, you should have the resulting
          document reviewed by qualified legal counsel before relying on it.
        </p>
        <h2>No attorney-client relationship</h2>
        <p>
          Using LOI Builder does not create an attorney-client relationship between you and LOI
          Builder or its creator. No communication through this site should be treated as legal
          counsel.
        </p>
        <h2>Your data</h2>
        <p>
          Form data you enter is used only to generate your document and is not sold to third
          parties.
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
