import { auth } from "../../lib/auth";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";

export const metadata = {
  title: "Support — LOI Builder",
  description: "Frequently asked questions and how to get help with LOI Builder.",
};

const FAQS = [
  {
    q: "Is LOI Builder really free?",
    a: "Yes — there's no subscription and no per-document fee. Sign in with a free account, fill out the form, and preview the document live for free.",
  },
  {
    q: "Is the document generated by LOI Builder legally binding?",
    a: "No. It's a non-binding Letter of Intent intended to outline preliminary terms. See our Legal & Disclaimer page for details.",
  },
  {
    q: "What export formats are supported?",
    a: "Word (.docx), PDF, and Google Doc.",
  },
  {
    q: "Does LOI Builder save my draft?",
    a: "Yes — sign in with a free account and your deal saves automatically. You can pick up where you left off from your dashboard on any device.",
  },
  {
    q: "I found a bug or have a question — how do I reach you?",
    a: "Email us at the address below and we'll get back to you.",
  },
];

export default async function SupportPage() {
  const session = await auth();
  const isLoggedIn = !!session?.user;

  return (
    <>
      <SiteHeader isLoggedIn={isLoggedIn} />
      <main className="marketing-page">
        <h1>Support</h1>
        {FAQS.map((item, i) => (
          <div key={i}>
            <h2>{item.q}</h2>
            <p>{item.a}</p>
          </div>
        ))}
        <p>
          <a href="mailto:support@loibuilder.app">Contact us at support@loibuilder.app</a>
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
