import { auth } from "../../lib/auth";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";

export const metadata = {
  title: "Support — Ledgerlot",
  description: "Frequently asked questions and how to get help with Ledgerlot.",
};

const FAQS = [
  {
    q: "How much does Ledgerlot cost?",
    a: "Personal accounts are pay-as-you-go — $2.00 per document, no subscription, up to 30/month. Business accounts are billed per seat, starting at $30/seat/month for small teams and dropping as you grow; every business plan starts with a 7-day free trial. See the Pricing page for the live breakdown.",
  },
  {
    q: "Is the document generated by Ledgerlot legally binding?",
    a: "A Letter of Intent is intentionally non-binding — it's meant to outline preliminary terms before a formal agreement. Leases and other documents you draft or upload and send for signature can be legally binding once signed; see our Legal & Disclaimer page for details.",
  },
  {
    q: "What kinds of documents can I build?",
    a: "A combined Business + Real Estate Purchase LOI, a Commercial Lease LOI, and a New Brunswick Residential Lease (standard form) — plus any of your own PDF forms, uploaded and turned into a reusable template.",
  },
  {
    q: "What export formats are supported?",
    a: "Word (.docx) and PDF.",
  },
  {
    q: "How does e-signature work?",
    a: "Send a document to one or more signers in a set order — each signer is notified only once it's their turn. Every signature is logged with a tamper-evident hash, and a Certificate of Completion is generated once everyone has signed.",
  },
  {
    q: "Do I need a password?",
    a: "No — sign in with an emailed link by default. You can optionally set a password later from Settings for a faster sign-in; the emailed link keeps working either way.",
  },
  {
    q: "Does Ledgerlot save my draft?",
    a: "Yes — sign in with a free account and your deal saves automatically. You can pick up where you left off from your Ledgerboard on any device.",
  },
  {
    q: "I found a bug or have a question — how do I reach you?",
    a: "Email us at the address below and we'll get back to you.",
  },
];

export default async function SupportPage() {
  const session = await auth();
  const isLoggedIn = !!session?.user;

  return (
    <>
      <SiteHeader isLoggedIn={isLoggedIn} />
      <main className="marketing-page">
        <h1>Support</h1>
        {FAQS.map((item, i) => (
          <div key={i}>
            <h2>{item.q}</h2>
            <p>{item.a}</p>
          </div>
        ))}
        <p>
          <a href="mailto:abhi@menonrealty.ca">Contact us at abhi@menonrealty.ca</a>
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
