import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";

export const metadata = {
  title: "Support — LOI Builder",
  description: "Frequently asked questions and how to get help with LOI Builder.",
};

const FAQS = [
  {
    q: "Is LOI Builder really free?",
    a: "Yes — there's no account and no subscription. Fill out the form and preview the document live for free.",
  },
  {
    q: "Is the document generated by LOI Builder legally binding?",
    a: "No. It's a non-binding Letter of Intent intended to outline preliminary terms. See our Legal & Disclaimer page for details.",
  },
  {
    q: "What export formats are supported?",
    a: "Word (.docx), PDF, and Google Doc.",
  },
  {
    q: "Does LOI Builder save my draft?",
    a: "Not yet — save/resume a draft via a shareable link is planned. See What's in v1 for the current feature set.",
  },
  {
    q: "I found a bug or have a question — how do I reach you?",
    a: "Email us at the address below and we'll get back to you.",
  },
];

export default function SupportPage() {
  return (
    <>
      <SiteHeader />
      <main className="marketing-page">
        <h1>Support</h1>
        {FAQS.map((item, i) => (
          <div key={i}>
            <h2>{item.q}</h2>
            <p>{item.a}</p>
          </div>
        ))}
        <p>
          <a href="mailto:support@loibuilder.app">Contact us at support@loibuilder.app</a>
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
